---
kind: pipeline
type: docker
name: default

steps:
    - name: docker
      image: plugins/docker
      tag: "${DRONE_BRANCH/master/latest}"
      settings:
          repo: cell/playground
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
