#!/bin/bash
#Provide the default parameters used by the image.

echo "docker run -ti --rm \
	-h dsb \
	-w \$PWD -v \$PWD:\$PWD \
	-v /etc/localtime:/etc/localtime:ro \
	-v \$HOME/.ssh:\$HOME/.ssh \
	-e USER -e UID=\$(id --user) -e GID=\$(id --group) \
	-v \$(which docker):\$(which docker) -v /var/run/docker.sock:/var/run/docker.sock \
	$@ \
	cell/debsandbox"

