#!/bin/bash
#Script to deploy payload/* on the machine.
set -e
readonly DEPLOY_DIR=/deploydir

usage() {
  echo "This script can only be used like this: docker run --rm --entrypoint deploy -v /usr/local/bin:${DEPLOY_DIR} ${DOCKER_IMAGE}"
}

if [ ! -d ${DEPLOY_DIR} -o "root" != "$(whoami)" ]; then
  usage
  exit 1
fi

cp /opt/payload/deploy/* ${DEPLOY_DIR}/
chmod a+x ${DEPLOY_DIR}/*

echo "Launcher in place, now you can use the command(s): $(find /usr/local/bin/ -maxdepth 1 -printf "%p " | sed 's/[^ ]*\/\([^/]*\) /\1 /g')"
