#!/bin/bash
#Script to deploy payload/* on the machine.
set -e
readonly DEPLOY_DIR=/deploydir

usage() {
  echo "This script can only be used like this: docker run --rm --entrypoint deploy -v /usr/local/bin:${DEPLOY_DIR} ${DOCKER_IMAGE}"
}

if [ ! -d ${DEPLOY_DIR} -o "root" != "$(whoami)" ]; then
  usage
  exit 1
fi

chmod a+x /opt/payload/deploy/*
cp /opt/payload/deploy/* ${DEPLOY_DIR}/

echo "Launcher in place, now you can use the command(s): $(find /opt/payload/deploy -maxdepth 1 -type f -printf "%p " | sed 's/[^ ]*\/\([^/]*\) /\1 /g')"
