#!/bin/bash

echo "A lot of options are needed to start this image.

  Default options for user are provided by: \"docker run --rm cell/debsandbox --cmd\"
  It s recommanded to use the start sript provided at the root of the repo. You can copy or link it to /usr/local/bin .

  Options and Tools:
    $(find /usr/local/bin/ -maxdepth 1 -printf "%p " | sed 's/[^ ]*\/\([^/]*\) /\1 /g')

  Packages:
     $(cat /var/log/apt/history.log | grep "apt-get install" | sed 's/^.*-qy //' | awk '{ printf("%s ", $0);}')

  Docker options:
    For using your user inside the container: -e USER -e UID=\$(id --user) -e GID=\$(id --group)
    For being in the current directory: -w \$PWD -v \$PWD:\$PWD
    For SSH: -v \$HOME/.ssh:\$HOME/.ssh -v \$SSH_AUTH_SOCK:\$SSH_AUTH_SOCK -e SSH_AUTH_SOCK
    For git settings: -v \$HOME/.gitconfig:\$HOME/.gitconfig
    For using docker: -v \$(which docker):\$(which docker) -v /var/run/docker.sock:/var/run/docker.sock
    For allowing X applications: -e XAUTHORITY -v \$XAUTHORITY:\$XAUTHORITY -e DISPLAY=/unix\$DISPLAY -e XSOCK -v /tmp/.X11-unix:/tmp/.X11-unix
    For changing the default shell (if there s no command) -e SHELL=...
    For debug: -e DEBUG=1
"

